
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
      # REDIS_URL: redis://redis:6379
      # ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "3000:3000"  # Expose port 3000 to access the NestJS API
    depends_on:
      - postgres
      # - redis
      # - elasticsearch
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose port 5432 for local dev
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent volume

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"  # Expose Redis port
  #   networks:
  #     - app-network

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
  #   container_name: elasticsearch
  #   environment:
  #     discovery.type: single-node
  #   ports:
  #     - "9200:9200"  # Expose Elasticsearch port
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
